name: Compile Mermaid Diagrams

on:
  push:
    branches:
      - main # or master, or any branch you want this to run on
    paths:
      - 'mind-maps/*.mermaid'
      - 'mind-maps/*.mmd'
      - 'illustrations/*.mermaid'
      - 'illustrations/*.mmd'
  workflow_dispatch:
    inputs:
      output_format:
        description: 'Output format (png, svg, pdf)'
        required: false
        default: 'png'
        type: choice
        options:
          - png
          - svg
          - pdf

jobs:
  compile_mermaid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mermaid-cli
        run: |
          npm install -g @mermaid-js/mermaid-cli

      - name: Set output format
        id: set_format
        run: |
          OUTPUT_FORMAT="${{ github.event.inputs.output_format || 'png' }}"
          echo "output_format=$OUTPUT_FORMAT" >> $GITHUB_OUTPUT

      - name: Compile mind-maps
        run: |
          OUTPUT_FORMAT="${{ steps.set_format.outputs.output_format }}"
          mkdir -p compiled-diagrams/mind-maps
          for file in mind-maps/*.mermaid mind-maps/*.mmd; do
            if [ -f "$file" ]; then
              base_name=$(basename "$file" .mermaid)
              base_name=$(basename "$base_name" .mmd)
              output_file="compiled-diagrams/mind-maps/${base_name}.${OUTPUT_FORMAT}"
              echo "Compiling $file to $output_file"
              # ADDED --no-sandbox HERE
              mmdc -i "$file" -o "$output_file" -t default --no-sandbox || true
            fi
          done
        continue-on-error: true # Allow the job to continue even if a single compilation fails

      - name: Compile illustrations
        run: |
          OUTPUT_FORMAT="${{ steps.set_format.outputs.output_format }}"
          mkdir -p compiled-diagrams/illustrations
          for file in illustrations/*.mermaid illustrations/*.mmd; do
            if [ -f "$file" ]; then
              base_name=$(basename "$file" .mermaid)
              base_name=$(basename "$base_name" .mmd)
              output_file="compiled-diagrams/illustrations/${base_name}.${OUTPUT_FORMAT}"
              echo "Compiling $file to $output_file"
              # ADDED --no-sandbox HERE
              mmdc -i "$file" -o "$output_file" -t default --no-sandbox || true
            fi
          done
        continue-on-error: true

      - name: Upload compiled diagrams
        uses: actions/upload-artifact@v4
        with:
          name: compiled-mermaid-diagrams-${{ steps.set_format.outputs.output_format }}
          path: compiled-diagrams/
          retention-days: 5
          if-no-files-found: warn