name: Generate PDFs from MD
on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    container:
      image: docker://pandoc/extra
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v2
      - name: prepare output directories
        run: |
          for d in */; do
            mkdir -p output/$d
          done
      - name: convert md to pdf with eisvogel template
        run: |
          find ./ -iname '*.md' -type f -exec sh -c 'pandoc ${0} -o output/${0%.md}.pdf --from markdown+table_captions --template /.pandoc/templates/eisvogel --listings' {} \;
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output